### ISSUE TITLE
Implement Foundry RPC

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/foundry#107]
Currently, Foundry is using CodeChain SDK in e2e tests. 

Let's create `foundry-rpc-js` project and use it in the e2e tests. We can fork `codechain-rpc-js` code and remove some RPCs that are removed from Foundry.

**Comment by majecty** [comment]
We can check removed RPCs in Foundry using the git command below:
`git log --graph -p rpc/`

**Comment by MSNTCS** [comment]
@majecty here is the list of rpcs that is removed or added: if there is nothing means it has been removed if there is Add means it is added.
chain:
chain_getAssetSchemeByTracker
chain_getAssetSchemeByType
chain_getText
chain_getAsset
chain_isAssetSpent
chain_executeVM


devel
Add: devel_snapshot


Miner:
miner_getWork
miner_submitWork

Add Snapshot

net:
Nothing

**Comment by MSNTCS** [comment]
> @majecty here is the list of rpcs that is removed or added: if there is nothing means it has been removed if there is Add means it is added.
> chain:
> chain_getAssetSchemeByTracker
> chain_getAssetSchemeByType
> chain_getText
> chain_getAsset
> chain_isAssetSpent
> chain_executeVM
> 
> devel:
> Add: devel_snapshot
> 
> miner:
> miner_getWork
> miner_submitWork
> 
> Add Snapshot.
> 
> net:
> Nothing

You mentioned, it should be 17 rpcs, but I found 10 rpcs.

**Comment by majecty** [comment]
17 was an example value. There was no meaning. Please go ahead.

**Comment by MSNTCS** [comment]
We need to decide what we should do for rpc adaptation to some parts of sdk, like `sdk.core`, `sdk.key`. There are no equivalent procedures in foundry-rpc.  
We also have to keep some parts of tests as same as before due to their complicated procedure or we need to design a strategy to modify it based on foundry-rpc.

**Comment by majecty** [comment]
IMO, we'd better replace only simple RPC use cases in Foundry to use foundry-rpc and change other things later.

**Comment by MSNTCS** [comment]
Here is the list of missing or troublesome functions of foundry rpc:
1- To sign transaction we still need SDK
`sdk.rpc.account.sign`
2- There is no method for getBlock.
`sdk.rpc.chain.getBlock(blockHash!)`
3- `engine.getBlockReward`
4- `chain.getPendingTransactions()`
5- `sendSignedTransaction`
6- `getRegularKey`. If we use foundry rpc, it would lead to Invalid checksum.
7- `chain_getCommonParams` returns CommonParams which has different attributes in sdk while there are not the same attributes for foundry rpc
8- `sdk.rpc.chain.getTransaction` returns `SignedTransaction` with different attributes while foundry does not have.
9- functionality of `devel.stopSealing` and `startSealing`. It seems they do not work properly. 
10- `sdk.rpc.network.getPeers()` 
11- `chain.getErrorHint`
12- `sdk.rpc.chain.getTransactionResultsByTracker`

**Comment by MSNTCS** [comment]
This PR is closed due to changes in the following list:
https://github.com/CodeChain-io/foundry/pull/189
https://github.com/CodeChain-io/foundry/pull/186
https://github.com/CodeChain-io/foundry/pull/184
https://github.com/CodeChain-io/foundry/pull/183
https://github.com/CodeChain-io/foundry/pull/176
https://github.com/CodeChain-io/foundry/pull/130
