### ISSUE TITLE
Refactor `Deref` to be generated automatically.

### ISSUE THREAD

**Issue by junha1** [CodeChain-io/foundry#187]
```rust
use std::marker::PhantomData;
use std::ops::{Deref, DerefMut};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ModuleUniqueIdentifier;

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct NewType<T, I>(T, PhantomData<I>);
impl<T, I> NewType<T, I> {
    pub fn new(x: T) -> Self {
        Self(x, PhantomData)
    }
}

impl<T, I> Deref for NewType<T, I> {
    type Target = T;
    fn deref(&self) -> &T {
        &self.0
    }
}
```
We've been using `Deref` for a new type, (which is not that recommended) and this requires trivial `impl` everytime.

Here's a simple idea:
Whenever you wanna make a new type, instead of manually implementing `Deref` or (`DerefMut`), you can just use this.

Here's an example.
```rust
pub type SomeIntegerThatIWantToSpeciallyUse = NewType<u64, ModuleUniqueIdentifier>;
```

This can remove most of repeated `impl Deref`s which appears quite often in Foundry. 

Note: you have to provide unique identifier type for each instance of `T`.

**Comment by majecty** [comment]
IMO, the `NewType` is not a Rust convention.
I like to implement the `Deref` every time we need it. We can manage them easily and other rust users can read and modify the code easily.

@kseo  @sgkim126 @HoOngEe @somniumism @MSNTCS @Byeongjee I want to hear your opinion.

**Comment by junha1** [comment]
Here's an alternative way (which we haven't used)
https://doc.rust-lang.org/rust-by-example/generics/new_types.html

**Comment by sgkim126** [comment]
We are using the new-type idiom in many cases, but the purpose of it is to make the compiler separate the new type with the underlying type.
And I cannot understand what your proposal fixes, it seems that it just makes the usage more complex. Would you explain the benefit again?

**Comment by junha1** [comment]
@sgkim126 for example
https://github.com/CodeChain-io/foundry/blob/master/core/src/scheme/pod_state.rs#L28
```rust
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct PodAccounts(BTreeMap<Address, PodAccount>);

impl Deref for PodAccounts {
    type Target = BTreeMap<Address, PodAccount>;

    fn deref(&self) -> &<Self as Deref>::Target {
        &self.0
    }
}
```
This will be
```rust
pub type PodAccounts = NewType<BTreeMap<Address, PodAccount>, ModuleUniqueIdentifier>;
```

**Comment by sgkim126** [comment]
My first impression is that the structure is ill-named. You proposed to provide the `Deref` implementation automatically, but the new-type pattern is to distinguish the types which have the same underlying type.

And it provides too restricted type. Since `NewType` derives `Clone`, `Debug`, `Eq`, and `PartialEq` only, the new type cannot derive other types. For instance, the `PodAccounts` derived `Default`, but it doesn't when the `NewType` is introduced. It can be compiled because the current code doesn't use the default method actually, but some types might be the problem.

The better and general solution in rust for this situation is creating a procedural macro. To know how to create the custom derive macro, I recommend you to read https://doc.rust-lang.org/1.30.0/book/2018-edition/appendix-04-macros.html#procedural-macros-for-custom-derive

**Comment by junha1** [comment]
@sgkim126 Ok, procedural macros seem the best (but requiring some time to learn) solution.
I really hope to have some time to introduce many helpful macros, including https://github.com/CodeChain-io/foundry/issues/99

**Comment by HoOngEe** [comment]
I agree with the macro implementation. I've met many trait impl bundles in other projects and often they looks fine.

**Comment by foriequal0** [comment]
https://crates.io/crates/derive_deref might be the crate that you are looking for.

**Comment by junha1** [comment]
Thank you for your idea everybody. I think it has to be handled with macro (or library that uses macro).
