### ISSUE TITLE
Optimize the sync module by not considering the score

### ISSUE THREAD

**Issue by HoOngEe** [CodeChain-io/foundry#243]
Since we decided to remove the concept of the score, we have some optimization points in the `sync` module. After #236 is merged, one can get down to this work.

**Comment by MSNTCS** [comment]
@majecty Is there any better explanation for this issue. The description of the issue is not informative. I cannot manage it. By any chance do you know what is the purpose of this issue?

**Comment by majecty** [comment]
What I understand is that "Sync module used 'score' before. Score was a difficulty to make a block from genesis in PoW context. Since Foundry does not use PoW, we removed the score. However, we just removed the score without considering the whole behavior of the sync. There may be some points that can be optimized since we removed the score."

**Comment by MSNTCS** [comment]
Since the optimization point being described by the author is not clear. We cannot proceed with this issue. Therefore, This issue should be closed.
