### ISSUE TITLE
Execute self-nomination transactions automatically

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/foundry#57]
We have a tool "auto-self-nominate" written in TypeScript.

We should run "auto-self-nominate" in a separate process from the CodeChain node. Since managing several processes costs a lot, running the same logic in the CodeChain process will reduce the overall managing cost.

**Comment by MSNTCS** [comment]
We need to have the same logic of `cron-jobs/auto-self-nominate/src/index.ts`.  Run a procedure like `send`  that checks whether the address is banned or in the jail, makes the address as a candidate, deposits then sends a self Nominate transaction.Therefore, we need some parameters to add to `codechain/codechain.yml`. These parameters are as follows:
- account-address
- passphrase
- default-metadata
- target-deposit
- interval

**Comment by majecty** [comment]
We need some prefixes. The current argument names are too general.

My suggestion(You can suggest better names).

* defualt-metadata -> self-nomination-metadata
* target-deposit -> self-nomination-target-deposit
* interval -> self-nomination-interval

Since CodeChain receives the validator address as `engine-signer` we don't need to receive it as `account-address`. Since CodeChain uses a password file to use a private key we don't need to use the `passphrase` argument.

**Comment by MSNTCS** [comment]
A new thread is designed to self auto self-nomination transactions. A node should enable the `enable-auto-self-nomination` argument in order to run the thread and add new metadata, deposit, and interval for new nomination. The thread checks whether the node is not jailed, is not banned, and is valid to be a candidate then sends a self-nomination transaction.
